service: serverless-graphql
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-include-dependencies

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - graphql-playground-middleware-express

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1

functions:
  purpledshub-graphql:
    handler: start.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
 # playground:
 #   handler: ./src/start.handler
  #  events:
  #    - http:
   #       path: playground
    #      method: get
